jwt.private.key=classpath:app.key
jwt.public.key=classpath:app.pub

app.base-url=http://127.0.0.1:5500/src/main/resources/static/index.html
spring.datasource.url= jdbc:mysql://localhost:3306/pollen
spring.datasource.username=ettore
spring.datasource.password=mylove
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.dialect=org.hibernate.dialect.MySQL5Dialect
spring.jpa.show-sql=true

springdoc.info.title=API de Processamento de Listas
springdoc.info.description=API REST para processar imagens contendo listas e gerar relatórios PDF
springdoc.info.version=1.0.0

springdoc.info.contact.name=Ettore Vitorio
springdoc.info.contact.email=contato@exemplo.com
springdoc.info.contact.url=https://github.com/veetorio/pollen-api

# Licença (opcional)
springdoc.info.license.name=MIT
springdoc.info.license.url=https://opensource.org/licenses/MIT